name: tiktok_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  like_button: ^2.0.5


  english_words: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  freezed: ^2.5.7
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  image: ^4.2.0
  video_thumbnail: ^0.5.3
  chewie: ^1.8.5
  video_player: ^2.9.1
  http: ^1.2.2
  permission_handler: ^11.3.1
  web_socket_channel: ^3.0.1
  swipeable_page_route: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/avatars/
  - assets/posts/
  - assets/videos/
  fonts:
    - family: Tiktok
      fonts:
        - asset: assets/fonts/tiktok/TikTokText-Regular.otf
        - asset:  assets/fonts/tiktok/TikTokText-Medium.otf
        - asset:  assets/fonts/tiktok/TikTokText-Bold.otf
        - asset: assets/fonts/tiktok/TikTokDisplay-Regular.otf
        - asset:  assets/fonts/tiktok/TikTokDisplay-Medium.otf
        - asset:  assets/fonts/tiktok/TikTokDisplay-Bold.otf
        